baseurl: ""
port: 4002

defaults:
  -
    scope:
      path: "pages" # an empty string here means all files in the project
      type: "pages" # previously `post` in Jekyll 2.2.
    values:
      layout: "course"
      title: "Default Title"
      type: "addon"
      caption: "Please change both the title and caption using editor"